CREATE_TEMP_TABLE = """
    CREATE TEMP TABLE TEMP_NUMBERS_TO_QUERY(
    	NUMERO_TELEFONE INT64,
    );
"""

INSERT_DATA_INTO_TEMP_TABLE = """
    INSERT INTO TEMP_NUMBERS_TO_QUERY
    SELECT * FROM numbers_to_query;
"""


QUERY_NUMBERS = """
    WITH
    CTE_NUMBERS_TO_QUERY AS (
        SELECT
        TEMP_NUMBERS_TO_QUERY.NUMERO_TELEFONE,
        CASE
            WHEN TEMP_NUMBERS_TO_QUERY.NUMERO_TELEFONE//10000000 IN (300, 303, 800) THEN TEMP_NUMBERS_TO_QUERY.NUMERO_TELEFONE
            ELSE TEMP_NUMBERS_TO_QUERY.NUMERO_TELEFONE//100
        END AS CN_PREFIXO_MC
        FROM TEMP_NUMBERS_TO_QUERY),
    CTE_HISTORICO_PORTABILIDADE AS (
        SELECT
            HP.NUMERO_TELEFONE,
            HP.DATA_PORTABILIDADE,
            HP.CODIGO_PRESTADORA,
            ROW_NUMBER() OVER (PARTITION BY HP.NUMERO_TELEFONE ORDER BY HP.DATA_PORTABILIDADE DESC) AS RN
        FROM TB_HISTORICO_PORTABILIDADE HP
        JOIN CTE_NUMBERS_TO_QUERY NQ ON HP.NUMERO_TELEFONE = NQ.NUMERO_TELEFONE
        WHERE HP.DATA_PORTABILIDADE <= ?),
    CTE_PORTABILIDADE AS (
    SELECT
        NUMERO_TELEFONE,
        CODIGO_PRESTADORA
    FROM CTE_HISTORICO_PORTABILIDADE
        WHERE CTE_HISTORICO_PORTABILIDADE.RN = 1)
    SELECT
        CTE_NUMBERS_TO_QUERY.NUMERO_TELEFONE,
        CASE
            WHEN TB_CODIGO_PRESTADORAS.CODIGO_PRESTADORA IS NOT NULL THEN TB_CODIGO_PRESTADORAS.NOME_PRESTADORA
            WHEN TB_CNPJ_PRESTADORAS.CNPJ_PRESTADORA IS NOT NULL THEN TB_CNPJ_PRESTADORAS.NOME_PRESTADORA
            ELSE 'PRESTADORA NÃO ENCONTRADA'
        END AS NOME_PRESTADORA,
        CASE
            WHEN CTE_PORTABILIDADE.CODIGO_PRESTADORA IS NOT NULL THEN 1
            WHEN TB_FAIXA_NUMERACAO.CNPJ_PRESTADORA IS NOT NULL THEN 0
            ELSE -1
        END AS PORTADO
        FROM CTE_NUMBERS_TO_QUERY
        LEFT JOIN CTE_PORTABILIDADE ON CTE_NUMBERS_TO_QUERY.NUMERO_TELEFONE = CTE_PORTABILIDADE.NUMERO_TELEFONE
        LEFT JOIN TB_CODIGO_PRESTADORAS ON TB_CODIGO_PRESTADORAS.CODIGO_PRESTADORA = CTE_PORTABILIDADE.CODIGO_PRESTADORA
        LEFT JOIN TB_FAIXA_NUMERACAO ON CTE_NUMBERS_TO_QUERY.CN_PREFIXO_MC = TB_FAIXA_NUMERACAO.CN_PREFIXO_MC
        LEFT JOIN TB_CNPJ_PRESTADORAS ON TB_FAIXA_NUMERACAO.CNPJ_PRESTADORA = TB_CNPJ_PRESTADORAS.CNPJ_PRESTADORA;
"""
